### PR TITLE
Prevent race condition

### PR DESCRIPTION
**Pull request by sediah**
TestWriteRaceCondition will be failed before applying the patch.

### CODE REVIEW

**Comment by colinmarc** [comment]
So, if I understand correctly - this issue happens when `Write` returns an `ackError`, and then the calling code calls `Write` again? Shouldn't the `blockWriteStream` just be considered broken at that point?

But wouldn't this code in `Write` just keep returning the `ackError`, preventing us from getting to the race? I don't quite see it yet.

```go
if s.ackError != nil {
	return 0, s.ackError
}
```

**Comment by colinmarc** [comment]
Ahhhhh, I see it now. `s.ackError` hasn't been set at that point, and then we quit the acking thread without closing the channel.

**Comment by colinmarc** [comment]
I went a slightly different direction with the fix - hope you don't mind. Thanks so much for catching this!

**Comment by sediah** [comment]
Thanks! I'll try with this version.

**Pull request closed without merging**
