### PR TITLE
fix hadoop_common proto building and syntax proto warnings

### PR DESCRIPTION
**Pull request by XooR**
protoc error was:

```
protoc-gen-go: error:inconsistent package import paths: ".", "github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common"
```

### CODE REVIEW

**Comment by XooR** [comment]
My `protoc` version is:

```bash
# protoc --version
libprotoc 3.0.0
```

**Comment by colinmarc** [comment]
I think that must be a bug in an old version. I have:

```
$ protoc --version
libprotoc 3.5.1
```

Going to close this, but feel free to tell me if you think I'm wrong :)

**Comment by XooR** [comment]
I tried with 'protoc` version '3.6.1' but I still get same message.

Also I wanted to ask why you import have version in it (`v2`). Because of that I needed to do 'go get` and move it to `v2` subfolder?
I don't know if this is cause of problem.

I use go `1.11`

**Comment by colinmarc** [comment]
with 1.11, go get should work normally (that is, you should be able to go get and import `github.com/colinmarc/hdfs`.

**Comment by pengisgood** [comment]
I tried `make clean-protos; make` on ubuntu with protoc version 3.5.1.

I got the same error.

```
2020/05/11 12:01:24 protoc-gen-go: error:inconsistent package import paths: ".", "github.com/pengisgood/hdfs/internal/protocol/hadoop_common"
--go_out: protoc-gen-go: Plugin failed with status code 1.
Makefile:16: recipe for target 'internal/protocol/hadoop_hdfs/inotify.pb.go' failed
make: *** [internal/protocol/hadoop_hdfs/inotify.pb.go] Error 1
```

**Pull request closed without merging**
