### PR TITLE
Fix skip offset of file reader Seek()

### PR DESCRIPTION
**Pull request by mtnk2005**
The offset of Skip() should be a offset in the block.

### CODE REVIEW

**Comment by colinmarc** [comment]
Hi @mtnk2005, thanks for the contribution! Can you possibly construct a pathological test case that would fail without this fix?

**Comment by mtnk2005** [comment]
> Hi @mtnk2005, thanks for the contribution! Can you possibly construct a pathological test case that would fail without this fix?

ok, TestFileSeekSkip() added

**Comment by colinmarc** [comment]
@mtnk2005 thanks for the quick response. I just ran the test on master, and it passed: https://github.com/colinmarc/hdfs/actions/runs/5520037428

**Comment by mtnk2005** [comment]
> @mtnk2005 thanks for the quick response. I just ran the test on master (without the fix), and it passed: https://github.com/colinmarc/hdfs/actions/runs/5520037428

Hi @colinmarc, Sorry for the test, the "f.blockReader" is nil, so it didn't trigger the bug, I just fixed the test by adding a pre read(), so the "f.blockReader" != nil, and the bug should be triggered.

**Comment by colinmarc** [comment]
still passing :)

https://github.com/colinmarc/hdfs/actions/runs/5520869984

I don't have an HDFS cluster to offer for realtime testing, unfortunately.

**Comment by mtnk2005** [comment]
I modified and tested the code, now failed finally, please check:

[root@hadoop01 shanhuang]# ./hdfs.test -test.v -test.run TestFileSeekSkip
=== RUN   TestFileSeekSkip
2023/07/12 18:15:20 call seek
2023/07/12 18:15:20 call seek
2023/07/12 18:15:20 call skip 34 14 0
2023/07/12 18:15:20 skip 20
    file_reader_test.go:241:
        	Error Trace:	file_reader_test.go:241
        	Error:      	Not equal:
        	            	expected: "Moby"
        	            	actual  : "berg"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-Moby
        	            	+berg
        	Test:       	TestFileSeekSkip
--- FAIL: TestFileSeekSkip (0.04s)
FAIL

**Comment by colinmarc** [comment]
Ahhhh - I get it now. Thank you for cracking that nut! Having a reproducible test case made it much easier for me to understand the bug. I went with a slightly different fix in 13d9368869e6f7f0a8db9d92e52c2ab54dae483e.

**Pull request closed without merging**
